### ISSUE TITLE
Notion link in readme.md is private

### ISSUE THREAD

**Issue by EFox2413** [SoulDancer27/cultivation-simulator#4]
![image](https://github.com/SoulDancer27/cultivation-simulator/assets/4999145/dbbac025-ad0b-4c1d-8adb-bb8db4291f27)

**Comment by SoulDancer27** [comment]
Sorry, I'm bad an notion. It definitely says everyone in an organization, not just everyone. Will try to fix it

![image](https://github.com/SoulDancer27/cultivation-simulator/assets/34806883/771b1498-c481-4589-a458-7288f566abe1)

**Comment by SoulDancer27** [comment]
https://www.notion.so/invite/48b707e7d61c4fd485c68b9adc7fb3e0e8856bea

an invite link

**Comment by SoulDancer27** [comment]
I've added an invite link to the project readme, I have no idea how to make a public workspace in Notion, hope, that works for now )

**Comment by EFox2413** [comment]
Thanks, the invite link works
